# OSINT Story Aggregator Configuration

# Data Sources
sources:
  # NewsAPI - Aggregates from 80k+ news sources (free tier available)
  newsapi:
    enabled: true
    api_key: "${NEWSAPI_KEY}"  # Set in .env file or leave empty for demo
    queries:
      - "APT cyber attack"
      - "nation state hacking"
      - "ransomware infrastructure"
      - "zero-day exploit"
      - "cyber espionage campaign"
      - "state sponsored threat"
    language: "en"
    page_size: 100

  # GDELT - Global news and events database (no API key required)
  gdelt:
    enabled: true
    queries:
      - "APT cyber attack"
      - "nation state hacking"
      - "ransomware attack"
      - "critical infrastructure cyber"
      - "cyber espionage"
      - "zero-day vulnerability"
    max_records: 50  # Reduced from 250 to prevent correlation timeout

  # Web scrapers for specific OSINT sources
  scrapers:
    enabled: true
    targets:
      - name: "Google News"
        type: "google_news"
        queries:
          - "China cyber espionage"
          - "Russia APT attack"
          - "Iran hacking group"
          - "North Korea cyber"
          - "Salt Typhoon APT"
          - "Volt Typhoon China"
        max_results: 50

      - name: "Bing News"
        type: "bing_news"
        queries:
          - "APT malware attack"
          - "nation state cyber threat"
          - "ransomware critical infrastructure"
          - "supply chain cyber attack"
          - "state sponsored hacking"
        max_results: 50

# Processing settings
processing:
  # Minimum similarity score to consider stories related (0.0-1.0)
  # Lower values (0.1-0.2) find more connections, higher values (0.4+) are stricter
  similarity_threshold: 0.15

  # Maximum age of stories to process (in hours)
  max_story_age_hours: 48

  # Maximum total stories to correlate (prevents timeout with large datasets)
  max_stories_to_correlate: 300

  # Content filtering - require at least one of these keywords for OSINT focus
  required_keywords:
    - cyber
    - hack
    - APT
    - malware
    - ransomware
    - breach
    - espionage
    - threat
    - vulnerability
    - exploit
    - zero-day
    - attack
    - intrusion
    - nation-state
    - intelligence
    - critical infrastructure
    - SCADA
    - ICS
    - phishing
    - spear-phishing

  # Entity extraction settings
  entity_types:
    - PERSON
    - ORG
    - GPE  # Geopolitical entity (countries, cities)
    - LOC  # Non-GPE locations
    - EVENT
    - DATE

  # Language filter (ISO codes)
  languages:
    - en

# Output settings
output:
  format: "both"  # json, html, or both
  directory: "data/output"

  # Generate report files
  reports:
    timeline: true
    clusters: true
    entity_graph: true

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/aggregator.log"
