name: Demo Run (Manual)

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI
    inputs:
      collectors:
        description: 'Which collectors to enable (newsapi,gdelt,scrapers or all)'
        required: false
        default: 'gdelt,scrapers'
      similarity_threshold:
        description: 'Similarity threshold (0.0-1.0)'
        required: false
        default: '0.15'

jobs:
  demo-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file (without real API keys)
      run: |
        echo "NEWSAPI_KEY=" > .env

    - name: Run aggregator demo
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      run: |
        python aggregator.py || echo "Demo run completed (may have warnings)"

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: demo-results
        path: |
          data/output/
          logs/
        retention-days: 7

    - name: Display summary
      if: always()
      run: |
        echo "## Demo Run Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f data/output/summary_*.json ]; then
          echo "✅ Summary file generated:" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat data/output/summary_*.json 2>/dev/null | head -20 >> $GITHUB_STEP_SUMMARY || echo "No summary available"
          echo '```' >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ No summary file generated" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Download artifacts to see full results" >> $GITHUB_STEP_SUMMARY
